name: Deploy Lambda Functions

on:
  push:
    branches:
      - master

jobs:
  deploy-lambdas:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: us-east-1 

      - name: Package Lambda function
        run: |
          zip -r wild-oasis-auth.zip wild-oasis-backend/wild-oasis-auth-function/build/
          

      - name: Deploy Lambda wild-oasis-auth
        run: |
          aws lambda update-function-code \
            --function-name wild-oasis-auth \
            --zip-file fileb://wild-oasis-auth.zip
